services:
    postgres-sso:
        image: postgres:alpine
        ports:
            - 5432:5432
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
            interval: 1s
            timeout: 5s
            retries: 3
        networks:
            - shared-net
    redis-sso:
        image: redis:latest
        ports:
            - 6379:6379
        restart: always
        env_file:
            - .env
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 1s
            timeout: 3s
            retries: 5
        networks:
            - shared-net

    migrator:
        image: migrate/migrate
        networks:
            - shared-net
        env_file:
            - .env
        depends_on:
            postgres-sso:
                condition: service_healthy
        volumes:
            - ./migrations:/migrations
        command:
            [
                "-path",
                "/migrations/",
                "-database",
                "postgres://${DB_USER}:${DB_PASSWORD}@postgres-sso:5432/${DB_NAME}?sslmode=disable",
                "up",
            ]

    sso:
        build: .
        ports:
            - "1337:1337"
            - "7171:7171"
        volumes:
            - ./storage:/app/storage
            - ./config:/app/config
        env_file:
            - .env
        environment:
            - PGSSLMODE=disable
        networks:
            - shared-net
        depends_on:
            migrator:
                condition: service_completed_successfully
            redis-sso:
                condition: service_healthy

networks:
    shared-net:
        external: true
