version: "3"

tasks:
    migrateUp:
        aliases:
            - up
        desc: "Apply all migrations"
        cmds:
            - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
    migrateDown:
        aliases:
            - down
        desc: "Rollback all migrations"
        cmds:
            - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations -down

    build:
        aliases:
            - bl
        desc: "Build main.go"
        cmds:
            - go build -o bin/sso cmd/sso/main.go
    compose:
        desc: "docker-compose"
        cmds:
            - docker-compose down -v
            - docker-compose up -d --build
            - docker-compose logs -f
    proto:
        aliases:
            - gen
        desc: "Regenerate the gRPC contract"
        dir: api
        cmds:
            - protoc -I sso/v1 sso.proto --go_out=sso/v1 --go_opt=paths=source_relative --go-grpc_out=sso/v1 --go-grpc_opt=paths=source_relative
