// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: sso.proto

package ssov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	AppId         int64                  `protobuf:"varint,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_sso_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_sso_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*LoginRequest_Email
	//	*LoginRequest_Username
	Identifier    isLoginRequest_Identifier `protobuf_oneof:"identifier"`
	Password      string                    `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	AppId         int64                     `protobuf:"varint,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_sso_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetIdentifier() isLoginRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Identifier.(*LoginRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Identifier.(*LoginRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type isLoginRequest_Identifier interface {
	isLoginRequest_Identifier()
}

type LoginRequest_Email struct {
	Email string `protobuf:"bytes,1,opt,name=email,proto3,oneof"`
}

type LoginRequest_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"`
}

func (*LoginRequest_Email) isLoginRequest_Identifier() {}

func (*LoginRequest_Username) isLoginRequest_Identifier() {}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_sso_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type IsAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AppId         int64                  `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAdminRequest) Reset() {
	*x = IsAdminRequest{}
	mi := &file_sso_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAdminRequest) ProtoMessage() {}

func (x *IsAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAdminRequest.ProtoReflect.Descriptor instead.
func (*IsAdminRequest) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{4}
}

func (x *IsAdminRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IsAdminRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type IsAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAdmin       bool                   `protobuf:"varint,1,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAdminResponse) Reset() {
	*x = IsAdminResponse{}
	mi := &file_sso_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAdminResponse) ProtoMessage() {}

func (x *IsAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAdminResponse.ProtoReflect.Descriptor instead.
func (*IsAdminResponse) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{5}
}

func (x *IsAdminResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type RegisterAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAppRequest) Reset() {
	*x = RegisterAppRequest{}
	mi := &file_sso_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAppRequest) ProtoMessage() {}

func (x *RegisterAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAppRequest.ProtoReflect.Descriptor instead.
func (*RegisterAppRequest) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterAppRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *RegisterAppRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type RegisterAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         int64                  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAppResponse) Reset() {
	*x = RegisterAppResponse{}
	mi := &file_sso_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAppResponse) ProtoMessage() {}

func (x *RegisterAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAppResponse.ProtoReflect.Descriptor instead.
func (*RegisterAppResponse) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterAppResponse) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *RegisterAppResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type DeleteUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*DeleteUserRequest_UserId
	//	*DeleteUserRequest_Username
	//	*DeleteUserRequest_Email
	Identifier    isDeleteUserRequest_Identifier `protobuf_oneof:"identifier"`
	AppId         int64                          `protobuf:"varint,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_sso_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserRequest) GetIdentifier() isDeleteUserRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *DeleteUserRequest) GetUserId() int64 {
	if x != nil {
		if x, ok := x.Identifier.(*DeleteUserRequest_UserId); ok {
			return x.UserId
		}
	}
	return 0
}

func (x *DeleteUserRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Identifier.(*DeleteUserRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *DeleteUserRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Identifier.(*DeleteUserRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *DeleteUserRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type isDeleteUserRequest_Identifier interface {
	isDeleteUserRequest_Identifier()
}

type DeleteUserRequest_UserId struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof"`
}

type DeleteUserRequest_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"`
}

type DeleteUserRequest_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

func (*DeleteUserRequest_UserId) isDeleteUserRequest_Identifier() {}

func (*DeleteUserRequest_Username) isDeleteUserRequest_Identifier() {}

func (*DeleteUserRequest_Email) isDeleteUserRequest_Identifier() {}

type DeleteAdminRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*DeleteAdminRequest_UserId
	//	*DeleteAdminRequest_Username
	//	*DeleteAdminRequest_Email
	Identifier    isDeleteAdminRequest_Identifier `protobuf_oneof:"identifier"`
	AppId         int64                           `protobuf:"varint,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminRequest) Reset() {
	*x = DeleteAdminRequest{}
	mi := &file_sso_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminRequest) ProtoMessage() {}

func (x *DeleteAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdminRequest) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAdminRequest) GetIdentifier() isDeleteAdminRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *DeleteAdminRequest) GetUserId() int64 {
	if x != nil {
		if x, ok := x.Identifier.(*DeleteAdminRequest_UserId); ok {
			return x.UserId
		}
	}
	return 0
}

func (x *DeleteAdminRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Identifier.(*DeleteAdminRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *DeleteAdminRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Identifier.(*DeleteAdminRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *DeleteAdminRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type isDeleteAdminRequest_Identifier interface {
	isDeleteAdminRequest_Identifier()
}

type DeleteAdminRequest_UserId struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof"`
}

type DeleteAdminRequest_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"`
}

type DeleteAdminRequest_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

func (*DeleteAdminRequest_UserId) isDeleteAdminRequest_Identifier() {}

func (*DeleteAdminRequest_Username) isDeleteAdminRequest_Identifier() {}

func (*DeleteAdminRequest_Email) isDeleteAdminRequest_Identifier() {}

type DeleteAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         int64                  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppRequest) Reset() {
	*x = DeleteAppRequest{}
	mi := &file_sso_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppRequest) ProtoMessage() {}

func (x *DeleteAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppRequest) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAppRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_sso_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewToken      string                 `protobuf:"bytes,1,opt,name=new_token,json=newToken,proto3" json:"new_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_sso_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{12}
}

func (x *RefreshTokenResponse) GetNewToken() string {
	if x != nil {
		return x.NewToken
	}
	return ""
}

type UpdateRefreshTokenRequst struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRefreshTokenRequst) Reset() {
	*x = UpdateRefreshTokenRequst{}
	mi := &file_sso_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRefreshTokenRequst) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRefreshTokenRequst) ProtoMessage() {}

func (x *UpdateRefreshTokenRequst) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRefreshTokenRequst.ProtoReflect.Descriptor instead.
func (*UpdateRefreshTokenRequst) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateRefreshTokenRequst) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type UpdateRefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRefreshTokenResponse) Reset() {
	*x = UpdateRefreshTokenResponse{}
	mi := &file_sso_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRefreshTokenResponse) ProtoMessage() {}

func (x *UpdateRefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*UpdateRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateRefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type MakeAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AppId         int64                  `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeAdminRequest) Reset() {
	*x = MakeAdminRequest{}
	mi := &file_sso_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeAdminRequest) ProtoMessage() {}

func (x *MakeAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeAdminRequest.ProtoReflect.Descriptor instead.
func (*MakeAdminRequest) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{15}
}

func (x *MakeAdminRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MakeAdminRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type MakeAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeAdminResponse) Reset() {
	*x = MakeAdminResponse{}
	mi := &file_sso_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeAdminResponse) ProtoMessage() {}

func (x *MakeAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeAdminResponse.ProtoReflect.Descriptor instead.
func (*MakeAdminResponse) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{16}
}

func (x *MakeAdminResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_sso_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{17}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type VerifyEmailRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Email            string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	VerificationCode string                 `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	AppId            int64                  `protobuf:"varint,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifyEmailRequest) Reset() {
	*x = VerifyEmailRequest{}
	mi := &file_sso_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailRequest) ProtoMessage() {}

func (x *VerifyEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailRequest.ProtoReflect.Descriptor instead.
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{18}
}

func (x *VerifyEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyEmailRequest) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

func (x *VerifyEmailRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

// Confirming an address proves ownership of the account, so the response
// carries a session: the caller does not need the password a second time.
type VerifyEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailResponse) Reset() {
	*x = VerifyEmailResponse{}
	mi := &file_sso_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailResponse) ProtoMessage() {}

func (x *VerifyEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailResponse.ProtoReflect.Descriptor instead.
func (*VerifyEmailResponse) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{19}
}

func (x *VerifyEmailResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *VerifyEmailResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type GenerateNewVerificationCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	AppId         int64                  `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateNewVerificationCodeRequest) Reset() {
	*x = GenerateNewVerificationCodeRequest{}
	mi := &file_sso_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateNewVerificationCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateNewVerificationCodeRequest) ProtoMessage() {}

func (x *GenerateNewVerificationCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateNewVerificationCodeRequest.ProtoReflect.Descriptor instead.
func (*GenerateNewVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{20}
}

func (x *GenerateNewVerificationCodeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GenerateNewVerificationCodeRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_sso_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{21}
}

var File_sso_proto protoreflect.FileDescriptor

const file_sso_proto_rawDesc = "" +
	"\n" +
	"\tsso.proto\x12\x04auth\"v\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x15\n" +
	"\x06app_id\x18\x04 \x01(\x03R\x05appId\"+\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x85\x01\n" +
	"\fLoginRequest\x12\x16\n" +
	"\x05email\x18\x01 \x01(\tH\x00R\x05email\x12\x1c\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x15\n" +
	"\x06app_id\x18\x04 \x01(\x03R\x05appIdB\f\n" +
	"\n" +
	"identifier\"W\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"@\n" +
	"\x0eIsAdminRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\x03R\x05appId\",\n" +
	"\x0fIsAdminResponse\x12\x19\n" +
	"\bis_admin\x18\x01 \x01(\bR\aisAdmin\"R\n" +
	"\x12RegisterAppRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12!\n" +
	"\fredirect_uri\x18\x02 \x01(\tR\vredirectUri\"D\n" +
	"\x13RegisterAppResponse\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x03R\x05appId\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"\x89\x01\n" +
	"\x11DeleteUserRequest\x12\x19\n" +
	"\auser_id\x18\x01 \x01(\x03H\x00R\x06userId\x12\x1c\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x12\x16\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05email\x12\x15\n" +
	"\x06app_id\x18\x04 \x01(\x03R\x05appIdB\f\n" +
	"\n" +
	"identifier\"\x8a\x01\n" +
	"\x12DeleteAdminRequest\x12\x19\n" +
	"\auser_id\x18\x01 \x01(\x03H\x00R\x06userId\x12\x1c\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x12\x16\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05email\x12\x15\n" +
	"\x06app_id\x18\x04 \x01(\x03R\x05appIdB\f\n" +
	"\n" +
	"identifier\")\n" +
	"\x10DeleteAppRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x03R\x05appId\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"3\n" +
	"\x14RefreshTokenResponse\x12\x1b\n" +
	"\tnew_token\x18\x01 \x01(\tR\bnewToken\"?\n" +
	"\x18UpdateRefreshTokenRequst\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"A\n" +
	"\x1aUpdateRefreshTokenResponse\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"B\n" +
	"\x10MakeAdminRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\x03R\x05appId\",\n" +
	"\x11MakeAdminResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"n\n" +
	"\x12VerifyEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12+\n" +
	"\x11verification_code\x18\x02 \x01(\tR\x10verificationCode\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\x03R\x05appId\"]\n" +
	"\x13VerifyEmailResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"Q\n" +
	"\"GenerateNewVerificationCodeRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\x03R\x05appId\"\a\n" +
	"\x05Empty2\xb4\x06\n" +
	"\x04Auth\x129\n" +
	"\bRegister\x12\x15.auth.RegisterRequest\x1a\x16.auth.RegisterResponse\x120\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x126\n" +
	"\aIsAdmin\x12\x14.auth.IsAdminRequest\x1a\x15.auth.IsAdminResponse\x12B\n" +
	"\vRegisterApp\x12\x18.auth.RegisterAppRequest\x1a\x19.auth.RegisterAppResponse\x122\n" +
	"\n" +
	"DeleteUser\x12\x17.auth.DeleteUserRequest\x1a\v.auth.Empty\x124\n" +
	"\vDeleteAdmin\x12\x18.auth.DeleteAdminRequest\x1a\v.auth.Empty\x120\n" +
	"\tDeleteApp\x12\x16.auth.DeleteAppRequest\x1a\v.auth.Empty\x12K\n" +
	"\x12RefreshAccessToken\x12\x19.auth.RefreshTokenRequest\x1a\x1a.auth.RefreshTokenResponse\x12V\n" +
	"\x12UpdateRefreshToken\x12\x1e.auth.UpdateRefreshTokenRequst\x1a .auth.UpdateRefreshTokenResponse\x12<\n" +
	"\tMakeAdmin\x12\x16.auth.MakeAdminRequest\x1a\x17.auth.MakeAdminResponse\x12*\n" +
	"\x06Logout\x12\x13.auth.LogoutRequest\x1a\v.auth.Empty\x12B\n" +
	"\vVerifyEmail\x12\x18.auth.VerifyEmailRequest\x1a\x19.auth.VerifyEmailResponse\x12T\n" +
	"\x1bGenerateNewVerificationCode\x12(.auth.GenerateNewVerificationCodeRequest\x1a\v.auth.EmptyB4Z2github.com/synnfluxx/TrustMeBroID/api/sso/v1;ssov1b\x06proto3"

var (
	file_sso_proto_rawDescOnce sync.Once
	file_sso_proto_rawDescData []byte
)

func file_sso_proto_rawDescGZIP() []byte {
	file_sso_proto_rawDescOnce.Do(func() {
		file_sso_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sso_proto_rawDesc), len(file_sso_proto_rawDesc)))
	})
	return file_sso_proto_rawDescData
}

var file_sso_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_sso_proto_goTypes = []any{
	(*RegisterRequest)(nil),                    // 0: auth.RegisterRequest
	(*RegisterResponse)(nil),                   // 1: auth.RegisterResponse
	(*LoginRequest)(nil),                       // 2: auth.LoginRequest
	(*LoginResponse)(nil),                      // 3: auth.LoginResponse
	(*IsAdminRequest)(nil),                     // 4: auth.IsAdminRequest
	(*IsAdminResponse)(nil),                    // 5: auth.IsAdminResponse
	(*RegisterAppRequest)(nil),                 // 6: auth.RegisterAppRequest
	(*RegisterAppResponse)(nil),                // 7: auth.RegisterAppResponse
	(*DeleteUserRequest)(nil),                  // 8: auth.DeleteUserRequest
	(*DeleteAdminRequest)(nil),                 // 9: auth.DeleteAdminRequest
	(*DeleteAppRequest)(nil),                   // 10: auth.DeleteAppRequest
	(*RefreshTokenRequest)(nil),                // 11: auth.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),               // 12: auth.RefreshTokenResponse
	(*UpdateRefreshTokenRequst)(nil),           // 13: auth.UpdateRefreshTokenRequst
	(*UpdateRefreshTokenResponse)(nil),         // 14: auth.UpdateRefreshTokenResponse
	(*MakeAdminRequest)(nil),                   // 15: auth.MakeAdminRequest
	(*MakeAdminResponse)(nil),                  // 16: auth.MakeAdminResponse
	(*LogoutRequest)(nil),                      // 17: auth.LogoutRequest
	(*VerifyEmailRequest)(nil),                 // 18: auth.VerifyEmailRequest
	(*VerifyEmailResponse)(nil),                // 19: auth.VerifyEmailResponse
	(*GenerateNewVerificationCodeRequest)(nil), // 20: auth.GenerateNewVerificationCodeRequest
	(*Empty)(nil),                              // 21: auth.Empty
}
var file_sso_proto_depIdxs = []int32{
	0,  // 0: auth.Auth.Register:input_type -> auth.RegisterRequest
	2,  // 1: auth.Auth.Login:input_type -> auth.LoginRequest
	4,  // 2: auth.Auth.IsAdmin:input_type -> auth.IsAdminRequest
	6,  // 3: auth.Auth.RegisterApp:input_type -> auth.RegisterAppRequest
	8,  // 4: auth.Auth.DeleteUser:input_type -> auth.DeleteUserRequest
	9,  // 5: auth.Auth.DeleteAdmin:input_type -> auth.DeleteAdminRequest
	10, // 6: auth.Auth.DeleteApp:input_type -> auth.DeleteAppRequest
	11, // 7: auth.Auth.RefreshAccessToken:input_type -> auth.RefreshTokenRequest
	13, // 8: auth.Auth.UpdateRefreshToken:input_type -> auth.UpdateRefreshTokenRequst
	15, // 9: auth.Auth.MakeAdmin:input_type -> auth.MakeAdminRequest
	17, // 10: auth.Auth.Logout:input_type -> auth.LogoutRequest
	18, // 11: auth.Auth.VerifyEmail:input_type -> auth.VerifyEmailRequest
	20, // 12: auth.Auth.GenerateNewVerificationCode:input_type -> auth.GenerateNewVerificationCodeRequest
	1,  // 13: auth.Auth.Register:output_type -> auth.RegisterResponse
	3,  // 14: auth.Auth.Login:output_type -> auth.LoginResponse
	5,  // 15: auth.Auth.IsAdmin:output_type -> auth.IsAdminResponse
	7,  // 16: auth.Auth.RegisterApp:output_type -> auth.RegisterAppResponse
	21, // 17: auth.Auth.DeleteUser:output_type -> auth.Empty
	21, // 18: auth.Auth.DeleteAdmin:output_type -> auth.Empty
	21, // 19: auth.Auth.DeleteApp:output_type -> auth.Empty
	12, // 20: auth.Auth.RefreshAccessToken:output_type -> auth.RefreshTokenResponse
	14, // 21: auth.Auth.UpdateRefreshToken:output_type -> auth.UpdateRefreshTokenResponse
	16, // 22: auth.Auth.MakeAdmin:output_type -> auth.MakeAdminResponse
	21, // 23: auth.Auth.Logout:output_type -> auth.Empty
	19, // 24: auth.Auth.VerifyEmail:output_type -> auth.VerifyEmailResponse
	21, // 25: auth.Auth.GenerateNewVerificationCode:output_type -> auth.Empty
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_sso_proto_init() }
func file_sso_proto_init() {
	if File_sso_proto != nil {
		return
	}
	file_sso_proto_msgTypes[2].OneofWrappers = []any{
		(*LoginRequest_Email)(nil),
		(*LoginRequest_Username)(nil),
	}
	file_sso_proto_msgTypes[8].OneofWrappers = []any{
		(*DeleteUserRequest_UserId)(nil),
		(*DeleteUserRequest_Username)(nil),
		(*DeleteUserRequest_Email)(nil),
	}
	file_sso_proto_msgTypes[9].OneofWrappers = []any{
		(*DeleteAdminRequest_UserId)(nil),
		(*DeleteAdminRequest_Username)(nil),
		(*DeleteAdminRequest_Email)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sso_proto_rawDesc), len(file_sso_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sso_proto_goTypes,
		DependencyIndexes: file_sso_proto_depIdxs,
		MessageInfos:      file_sso_proto_msgTypes,
	}.Build()
	File_sso_proto = out.File
	file_sso_proto_goTypes = nil
	file_sso_proto_depIdxs = nil
}
